Improvements in the installation of the program and the launcher.
-The respective dependencies are now installed automatically.
-Now the virtual environment is prepared before the first start of the program.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,14 +1,14 @@
 #!/bin/bash
 
 if [ ! $EUID = 0 ]; then
-    echo "ERROR: Exec with root."
-    exit 1
+  echo "ERROR: Exec with root."
+  exit 1
 fi
 
 SH_PATH=$(dirname "$0")
 APP_PATH=/opt/Wallpaper-LX
 
-# necessary files
+# Necessary files
 APP_FOLDER_PATH=$SH_PATH/app/
 RESOURCES_FOLDER_PATH=$SH_PATH/resources/
 
@@ -20,17 +20,30 @@ APP_DESKTOP=$SH_PATH/wallpaper_lx.desktop
 echo "INFO: Starting installation..."
 
 if [ -d $APP_PATH ]; then
-    chmod +x "$SH_PATH/uninstall"
-    $SH_PATH/uninstall
-    echo "INFO: Existing version removed."
+  chmod +x "$SH_PATH/uninstall"
+  $SH_PATH/uninstall
+  echo "INFO: Existing version removed."
 fi
 
 mkdir $APP_PATH
 
+# Dependencies
+echo "INFO: Starting installation of dependencies."
+
+if [[ $(cat /etc/*-release) == *"debian"* ]]; then
+  apt-get update
+  apt-get install python3-pip python3-venv python3-tk python3-pil.imagetk git
+elif [[ $(cat /etc/*-release) == *"fedora"* ]]; then
+  dnf check-update
+  dnf install python3-pip python3-virtualenv python3-tkinter python3-imaging-tk git xrandr xdpyinfo -y
+else
+  echo "ERROR: The distribution could not be identified. The units could not be installed."
+fi
+
 IFS=$'\n' read -d '' -ra array <<< "$(cat $SH_PATH/appfiles.txt)"
 folderpath=$APP_PATH
 
-# Imprime el contenido del array
+# Print array content
 for element in "${array[@]}"; do
   if [ -d "$element" ]; then
     folderpath="$APP_PATH/$element"
@@ -50,6 +63,29 @@ for element in "${array[@]}"; do
   fi
 done
 
+# Make venv.
+if [ $HOME = /root ]; then
+  HOME=/home/$SUDO_USER
+  USER=$SUDO_USER
+fi
+
+VENV_PATH=$HOME/.config/Wallpaper-LX/.venv
+ACTIVATE_PATH=$VENV_PATH/bin/activate
+
+echo "INFO: Make venv."
+
+if [ -d $VENV_PATH ]; then
+  rm -r -dir --force $VENV_PATH
+fi
+
+python3 -m venv $VENV_PATH
+source $ACTIVATE_PATH
+pip3 install pillow --no-cache-dir
+deactivate
+
+chown -R $USER:$USER $VENV_PATH
+
+# Finish
 chmod +x $APP_PATH/Wallpaper-LX
 
 cp "$SH_PATH/icons/16x16/wallpaper-lx.png" /usr/share/icons/hicolor/16x16/apps/
diff --git a/uninstall b/uninstall
--- a/uninstall
+++ b/uninstall
@@ -1,38 +1,22 @@
 #!/bin/bash
 
 if [ ! $EUID = 0 ]; then
-    echo "ERROR: Exec with root."
-    exit 1
+  echo "ERROR: Exec with root."
+  exit 1
 fi
 
 if [ $HOME = /root ]; then
-    HOME=/home/$SUDO_USER
-fi
-
-# Remove app files
-if [ -d /opt/Wallpaper-LX ]; then
-    rm -r -dir --force /opt/Wallpaper-LX
-    echo "INFO: App uninstalled."
-else
-    echo "INFO: The app is not installed."
+  HOME=/home/$SUDO_USER
 fi
 
 # Remove venv files
-VENV_FILES=("$HOME/.config/Wallpaper-LX/bin" "$HOME/.config/Wallpaper-LX/include" "$HOME/.config/Wallpaper-LX/lib" "$HOME/.config/Wallpaper-LX/lib64" "$HOME/.config/Wallpaper-LX/share" "$HOME/.config/Wallpaper-LX/pyvenv.cfg")
+VENV_PATH=$HOME/.config/Wallpaper-LX/.venv
+if [ -d $VENV_PATH ]; then
+  rm -r -dir --force $VENV_PATH
+  echo "INFO: $VENV_PATH (removed)"
+fi
 
-for element in ${VENV_FILES[@]}; do
-    if [ -d $element ]; then
-        rm -r -dir --force $element
-        echo "INFO: $element (removed)"
-    elif [ -f $element ]; then
-        rm --force $element
-        echo "INFO: $element (removed)"
-    elif [ -h $element ]; then
-        rm --force $element
-        echo "INFO: $element (removed)"
-    fi
-done
-
+# Remove .desktop and icons
 rm --force /usr/share/icons/hicolor/16x16/apps/wallpaper-lx.png
 rm --force /usr/share/icons/hicolor/32x32/apps/wallpaper-lx.png
 rm --force /usr/share/icons/hicolor/48x48/apps/wallpaper-lx.png
@@ -40,6 +24,14 @@ rm --force /usr/share/icons/hicolor/128x128/apps/wallpaper-lx.png
 rm --force /usr/share/icons/hicolor/256x256/apps/wallpaper-lx.png
 
 if [ -f /usr/share/applications/wallpaper_lx.desktop ]; then
-    rm --force /usr/share/applications/wallpaper_lx.desktop
-    echo "INFO: /usr/share/applications/wallpaper_lx.desktop (removed)"
+  rm --force /usr/share/applications/wallpaper_lx.desktop
+  echo "INFO: /usr/share/applications/wallpaper_lx.desktop (removed)"
+fi
+
+# Remove app files
+if [ -d /opt/Wallpaper-LX ]; then
+  rm -r -dir --force /opt/Wallpaper-LX
+  echo "INFO: App uninstalled."
+else
+  echo "INFO: The app is not installed."
 fi
